version: '2'
services:
    blogs-app:
        image: blogs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blogs-mysql:3306/blogs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogs-mysql:
        extends:
            file: mysql.yml
            service: blogs-mysql
